### ISSUE TITLE
CRASH when empty services

### ISSUE THREAD

**Issue by Theosakamg** [upsun/clonsun#4]
```
WARNING: file 'applications.yaml' not found in directory '/tmp/cli-2997035632-tmp/repo/.platform'
2024/11/29 11:21:22 Discover found '.platform.app.yaml' at: /tmp/cli-2997035632-tmp/repo/.platform.app.yaml
2024/11/29 11:21:22 Discover found 'routes.yaml' at: /tmp/cli-2997035632-tmp/repo/.platform/routes.yaml
2024/11/29 11:21:22 Discover found 'services.yaml' at: /tmp/cli-2997035632-tmp/repo/.platform/services.yaml
2024/11/29 11:21:22 Clean up tempory workspace...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/upsun/lib-sun/readers.readConfigFile(0xc000031510, {0xc000139440?, 0x7d7073?})
	/go/pkg/mod/github.com/upsun/lib-sun@v0.3.11/readers/psh_config.go:43 +0x255
github.com/upsun/lib-sun/readers.ReadServices(...)
	/go/pkg/mod/github.com/upsun/lib-sun@v0.3.11/readers/psh_config.go:48
github.com/upsun/convsun/internal/logic.Convert({0xc000296060, 0x1c}, {0xc0001379e0, 0x23})
	/go/pkg/mod/github.com/upsun/convsun@v0.3.2/internal/logic/convert_config.go:30 +0x248
github.com/upsun/convsun/api.Convert(...)
	/go/pkg/mod/github.com/upsun/convsun@v0.3.2/api/api.go:6
github.com/upsun/clonsun/internal/logic.Clone({{0x7ffeb552dd0e, 0x8}, {0x0, 0x0}, {0x7ffeb552dd25, 0xd}, {0x0, 0x0}, {0x7ffeb552dd3d, 0x6}, ...}, ...)
	/github/workspace/internal/logic/clone_project.go:74 +0x7ca
main.main()
	/github/workspace/cmd/upsun_clone.go:158 +0x8bd
```

cc @vrobert78

**Comment by Theosakamg** [comment]
fix on 121830f8f14a84c8c8fb8cd6a319b9749e5b026f
